"""Scenario Definitions and Dataclasses for the Synthetic Validation Harness."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


class AnomalyCategory(str, Enum):
    """Broad categorization of synthetic validation scenarios."""
    BASELINE = "BASELINE"
    TEMPORAL_FAULT = "TEMPORAL_FAULT"
    PHYSICAL_LIMIT = "PHYSICAL_LIMIT"
    DATA_QUALITY = "DATA_QUALITY"
    MULTIVARIATE_FAULT = "MULTIVARIATE_FAULT"
    SPATIAL_FAULT = "SPATIAL_FAULT"
    GENUINE_METEOROLOGICAL_EVENT = "GENUINE_METEOROLOGICAL_EVENT"
    SOURCE_OR_NETWORK_OUTAGE = "SOURCE_OR_NETWORK_OUTAGE"


@dataclass
class ScenarioDefinition:
    """Authoritative metadata and expectations for a single synthetic validation scenario."""
    scenario_id: str
    name: str
    category: AnomalyCategory
    target_stations: List[str]
    description: str
    injection_start_step: int
    injection_end_step: int
    anomaly_type: str
    parameters: Dict[str, Any] = field(default_factory=dict)
    
    # Explicit 9-Dimensional Expectation Specifications
    expected_detection: bool = False
    expected_decision: str = "NORMAL"
    accepted_decisions: List[str] = field(default_factory=lambda: ["NORMAL"])
    expected_sensor_health_direction: str = "STABLE"  # STABLE, DECREASING, PROTECTED, RECOVERING
    expected_source_health: str = "HEALTHY"           # HEALTHY, DEGRADED, DISCONNECTED, STALE
    expected_correction: str = "NONE"                 # NONE, GENERATED
    expected_persistence: bool = True
    expected_websocket: bool = True
    
    # Metadata & Transport expectations
    expected_ws_event_type: str = "OBSERVATION_UPDATED"
    expected_qc_status: str = "VALID"
    isolation_expected: bool = True

    def to_dict(self) -> Dict[str, Any]:
        """Convert scenario definition to dictionary."""
        d = asdict(self)
        d["category"] = self.category.value
        return d


# 24 Definitive Synthetic Validation Scenarios (SV01 to SV24)
SCENARIO_DEFINITIONS: List[ScenarioDefinition] = [
    ScenarioDefinition(
        scenario_id="SV01",
        name="Clean Baseline",
        category=AnomalyCategory.BASELINE,
        target_stations=["AWS_DEL_001", "AWS_DEL_002", "AWS_DEL_003", "AWS_DEL_004", "AWS_DEL_005"],
        description="Plausible diurnal meteorological cycles with natural stochastic noise across all stations.",
        injection_start_step=0,
        injection_end_step=287,
        anomaly_type="NONE",
        expected_detection=False,
        expected_decision="NORMAL",
        accepted_decisions=["NORMAL"],
        expected_sensor_health_direction="STABLE",
        expected_source_health="HEALTHY",
        expected_correction="NONE",
        expected_ws_event_type="OBSERVATION_UPDATED",
        expected_qc_status="VALID",
    ),
    ScenarioDefinition(
        scenario_id="SV02",
        name="Isolated Positive Spike",
        category=AnomalyCategory.TEMPORAL_FAULT,
        target_stations=["AWS_DEL_001"],
        description="Sudden unphysical +12.0°C temperature spike on a single station while neighbors remain coherent.",
        injection_start_step=40,
        injection_end_step=41,
        anomaly_type="SPIKE_POSITIVE",
        parameters={"delta_temp_c": 12.0},
        expected_detection=True,
        expected_decision="PROBABLE_SENSOR_ANOMALY",
        accepted_decisions=["PROBABLE_SENSOR_ANOMALY"],
        expected_sensor_health_direction="DECREASING",
        expected_source_health="HEALTHY",
        expected_correction="GENERATED",
        expected_ws_event_type="ANOMALY_CREATED",
        expected_qc_status="VALID",
    ),
    ScenarioDefinition(
        scenario_id="SV03",
        name="Isolated Negative Drop",
        category=AnomalyCategory.TEMPORAL_FAULT,
        target_stations=["AWS_DEL_002"],
        description="Sudden unphysical -15.0°C temperature plunge on a single station.",
        injection_start_step=45,
        injection_end_step=46,
        anomaly_type="SPIKE_NEGATIVE",
        parameters={"delta_temp_c": -15.0},
        expected_detection=True,
        expected_decision="PROBABLE_SENSOR_ANOMALY",
        accepted_decisions=["PROBABLE_SENSOR_ANOMALY"],
        expected_sensor_health_direction="DECREASING",
        expected_source_health="HEALTHY",
        expected_correction="GENERATED",
        expected_ws_event_type="ANOMALY_CREATED",
        expected_qc_status="VALID",
    ),
    ScenarioDefinition(
        scenario_id="SV04",
        name="Persistent Step Change",
        category=AnomalyCategory.TEMPORAL_FAULT,
        target_stations=["AWS_DEL_003"],
        description="Persistent uncalibrated +8.0°C offset starting at step 50 and continuing for 12 cycles.",
        injection_start_step=50,
        injection_end_step=62,
        anomaly_type="STEP_CHANGE",
        parameters={"delta_temp_c": 8.0},
        expected_detection=True,
        expected_decision="PROBABLE_SENSOR_ANOMALY",
        accepted_decisions=["PROBABLE_SENSOR_ANOMALY"],
        expected_sensor_health_direction="DECREASING",
        expected_source_health="HEALTHY",
        expected_correction="GENERATED",
        expected_ws_event_type="ANOMALY_CREATED",
        expected_qc_status="VALID",
    ),
    ScenarioDefinition(
        scenario_id="SV05",
        name="Slow Sensor Drift",
        category=AnomalyCategory.TEMPORAL_FAULT,
        target_stations=["AWS_DEL_004"],
        description="Gradual monotonic drift of +0.3°C per 5-min step across 16 consecutive steps.",
        injection_start_step=65,
        injection_end_step=80,
        anomaly_type="DRIFT",
        parameters={"drift_rate_c_per_step": 0.3},
        expected_detection=True,
        expected_decision="PROBABLE_SENSOR_ANOMALY",
        accepted_decisions=["PROBABLE_SENSOR_ANOMALY"],
        expected_sensor_health_direction="DECREASING",
        expected_source_health="HEALTHY",
        expected_correction="GENERATED",
        expected_ws_event_type="ANOMALY_CREATED",
        expected_qc_status="VALID",
    ),
    ScenarioDefinition(
        scenario_id="SV06",
        name="Flatline / Frozen Sensor",
        category=AnomalyCategory.TEMPORAL_FAULT,
        target_stations=["AWS_DEL_005"],
        description="Constant frozen temperature/RH/pressure values repeated for 18 consecutive 5-min intervals.",
        injection_start_step=85,
        injection_end_step=102,
        anomaly_type="FLATLINE",
        expected_detection=True,
        expected_decision="PROBABLE_SENSOR_ANOMALY",
        accepted_decisions=["PROBABLE_SENSOR_ANOMALY"],
        expected_sensor_health_direction="DECREASING",
        expected_source_health="HEALTHY",
        expected_correction="GENERATED",
        expected_ws_event_type="ANOMALY_CREATED",
        expected_qc_status="VALID",
    ),
    ScenarioDefinition(
        scenario_id="SV07",
        name="High-Frequency Oscillation",
        category=AnomalyCategory.TEMPORAL_FAULT,
        target_stations=["AWS_NCR_006"],
        description="Rapid unphysical alternating ±7.5°C oscillations every 5 minutes for 10 cycles.",
        injection_start_step=70,
        injection_end_step=80,
        anomaly_type="OSCILLATION",
        parameters={"amplitude_c": 7.5},
        expected_detection=True,
        expected_decision="PROBABLE_SENSOR_ANOMALY",
        accepted_decisions=["PROBABLE_SENSOR_ANOMALY"],
        expected_sensor_health_direction="DECREASING",
        expected_source_health="HEALTHY",
        expected_correction="GENERATED",
        expected_ws_event_type="ANOMALY_CREATED",
        expected_qc_status="VALID",
    ),
    ScenarioDefinition(
        scenario_id="SV08",
        name="Rate-of-Change Violation",
        category=AnomalyCategory.TEMPORAL_FAULT,
        target_stations=["AWS_NCR_007"],
        description="Sudden temperature jump of 9.5°C in a single 5-minute interval exceeding physical limits.",
        injection_start_step=90,
        injection_end_step=91,
        anomaly_type="RATE_OF_CHANGE_VIOLATION",
        parameters={"jump_c": 9.5},
        expected_detection=True,
        expected_decision="PROBABLE_SENSOR_ANOMALY",
        accepted_decisions=["PROBABLE_SENSOR_ANOMALY"],
        expected_sensor_health_direction="DECREASING",
        expected_source_health="HEALTHY",
        expected_correction="GENERATED",
        expected_ws_event_type="ANOMALY_CREATED",
        expected_qc_status="VALID",
    ),
    ScenarioDefinition(
        scenario_id="SV09",
        name="Impossible Temperature Limit",
        category=AnomalyCategory.PHYSICAL_LIMIT,
        target_stations=["AWS_NCR_008"],
        description="Extreme near-limit reading (59.8°C) flagged as physical bound / hardware defect.",
        injection_start_step=95,
        injection_end_step=96,
        anomaly_type="IMPOSSIBLE_TEMPERATURE",
        parameters={"bad_temp_c": 59.8},
        expected_detection=True,
        expected_decision="PROBABLE_SENSOR_ANOMALY",
        accepted_decisions=["PROBABLE_SENSOR_ANOMALY", "PROBABLE_DATA_QUALITY_ISSUE"],
        expected_sensor_health_direction="DECREASING",
        expected_source_health="HEALTHY",
        expected_correction="GENERATED",
        expected_ws_event_type="ANOMALY_CREATED",
        expected_qc_status="ERROR",
    ),
    ScenarioDefinition(
        scenario_id="SV10",
        name="Invalid Relative Humidity",
        category=AnomalyCategory.PHYSICAL_LIMIT,
        target_stations=["AWS_NCR_009"],
        description="Unphysical relative humidity (99.9% sudden surge with ERROR QC status).",
        injection_start_step=100,
        injection_end_step=101,
        anomaly_type="INVALID_RH",
        parameters={"bad_rh_pct": 99.9},
        expected_detection=True,
        expected_decision="PROBABLE_DATA_QUALITY_ISSUE",
        accepted_decisions=["PROBABLE_DATA_QUALITY_ISSUE", "PROBABLE_SENSOR_ANOMALY"],
        expected_sensor_health_direction="DECREASING",
        expected_source_health="HEALTHY",
        expected_correction="GENERATED",
        expected_ws_event_type="ANOMALY_CREATED",
        expected_qc_status="ERROR",
    ),
    ScenarioDefinition(
        scenario_id="SV11",
        name="Invalid Pressure Limit",
        category=AnomalyCategory.PHYSICAL_LIMIT,
        target_stations=["AWS_NCR_010"],
        description="Severe barometric plunge to 875.0 hPa flagged as corrupted / physical violation.",
        injection_start_step=105,
        injection_end_step=106,
        anomaly_type="INVALID_PRESSURE",
        parameters={"bad_slp_hpa": 875.0},
        expected_detection=True,
        expected_decision="PROBABLE_DATA_QUALITY_ISSUE",
        accepted_decisions=["PROBABLE_DATA_QUALITY_ISSUE", "PROBABLE_SENSOR_ANOMALY"],
        expected_sensor_health_direction="DECREASING",
        expected_source_health="HEALTHY",
        expected_correction="GENERATED",
        expected_ws_event_type="ANOMALY_CREATED",
        expected_qc_status="ERROR",
    ),
    ScenarioDefinition(
        scenario_id="SV12",
        name="Missing Temperature Field",
        category=AnomalyCategory.DATA_QUALITY,
        target_stations=["AWS_REG_011"],
        description="Observation packet missing required temperature_c field.",
        injection_start_step=110,
        injection_end_step=111,
        anomaly_type="MISSING_TEMPERATURE",
        expected_detection=False,
        expected_decision="PROBABLE_DATA_QUALITY_ISSUE",
        accepted_decisions=["PROBABLE_DATA_QUALITY_ISSUE"],
        expected_sensor_health_direction="DECREASING",
        expected_source_health="HEALTHY",
        expected_correction="NONE",
        expected_ws_event_type="OBSERVATION_UPDATED",
        expected_qc_status="MISSING",
    ),
    ScenarioDefinition(
        scenario_id="SV13",
        name="Missing Relative Humidity Field",
        category=AnomalyCategory.DATA_QUALITY,
        target_stations=["AWS_REG_012"],
        description="Observation packet missing relative_humidity_pct field.",
        injection_start_step=112,
        injection_end_step=113,
        anomaly_type="MISSING_RH",
        expected_detection=False,
        expected_decision="PROBABLE_DATA_QUALITY_ISSUE",
        accepted_decisions=["PROBABLE_DATA_QUALITY_ISSUE"],
        expected_sensor_health_direction="STABLE",
        expected_source_health="HEALTHY",
        expected_correction="NONE",
        expected_ws_event_type="OBSERVATION_UPDATED",
        expected_qc_status="MISSING",
    ),
    ScenarioDefinition(
        scenario_id="SV14",
        name="Missing Pressure Field",
        category=AnomalyCategory.DATA_QUALITY,
        target_stations=["AWS_REG_013"],
        description="Observation packet missing sea_level_pressure_hpa field.",
        injection_start_step=114,
        injection_end_step=115,
        anomaly_type="MISSING_PRESSURE",
        expected_detection=False,
        expected_decision="PROBABLE_DATA_QUALITY_ISSUE",
        accepted_decisions=["PROBABLE_DATA_QUALITY_ISSUE"],
        expected_sensor_health_direction="STABLE",
        expected_source_health="HEALTHY",
        expected_correction="NONE",
        expected_ws_event_type="OBSERVATION_UPDATED",
        expected_qc_status="MISSING",
    ),
    ScenarioDefinition(
        scenario_id="SV15",
        name="Duplicate Observation",
        category=AnomalyCategory.DATA_QUALITY,
        target_stations=["AWS_REG_014"],
        description="Identical observation packet transmitted twice in succession.",
        injection_start_step=118,
        injection_end_step=118,
        anomaly_type="DUPLICATE",
        expected_detection=False,
        expected_decision="DUPLICATE_SKIPPED",
        accepted_decisions=["DUPLICATE_SKIPPED", "NORMAL", "PROBABLE_DATA_QUALITY_ISSUE"],
        expected_sensor_health_direction="STABLE",
        expected_source_health="HEALTHY",
        expected_correction="NONE",
        expected_ws_event_type="OBSERVATION_UPDATED",
        expected_qc_status="VALID",
    ),
    ScenarioDefinition(
        scenario_id="SV16",
        name="Out-of-Order Observation",
        category=AnomalyCategory.DATA_QUALITY,
        target_stations=["AWS_REG_015"],
        description="Observation with timestamp from 30 minutes in the past arriving out-of-order.",
        injection_start_step=120,
        injection_end_step=120,
        anomaly_type="OUT_OF_ORDER",
        parameters={"delay_minutes": 7},
        expected_detection=False,
        expected_decision="PROBABLE_DATA_QUALITY_ISSUE",
        accepted_decisions=["PROBABLE_DATA_QUALITY_ISSUE", "DUPLICATE_SKIPPED", "OUT_OF_ORDER"],
        expected_sensor_health_direction="STABLE",
        expected_source_health="HEALTHY",
        expected_correction="NONE",
        expected_ws_event_type="OBSERVATION_UPDATED",
        expected_qc_status="SUSPECT",
    ),
    ScenarioDefinition(
        scenario_id="SV17",
        name="Timestamp Gap",
        category=AnomalyCategory.DATA_QUALITY,
        target_stations=["AWS_REG_016"],
        description="Missing 45-minute communication silence followed by normal observation arrival.",
        injection_start_step=125,
        injection_end_step=133,
        anomaly_type="TIMESTAMP_GAP",
        parameters={"gap_minutes": 45},
        expected_detection=False,
        expected_decision="NORMAL",
        accepted_decisions=["NORMAL", "PROBABLE_DATA_QUALITY_ISSUE"],
        expected_sensor_health_direction="STABLE",
        expected_source_health="HEALTHY",
        expected_correction="NONE",
        expected_ws_event_type="OBSERVATION_UPDATED",
        expected_qc_status="VALID",
    ),
    ScenarioDefinition(
        scenario_id="SV18",
        name="Corrupted Timestamp String",
        category=AnomalyCategory.DATA_QUALITY,
        target_stations=["AWS_REG_017"],
        description="Malformed ISO timestamp triggering rejection at ingestion boundary.",
        injection_start_step=135,
        injection_end_step=135,
        anomaly_type="CORRUPTED_TIMESTAMP",
        parameters={"bad_timestamp": "2026-99-99T99:99:99Z"},
        expected_detection=False,
        expected_decision="PROBABLE_DATA_QUALITY_ISSUE",
        accepted_decisions=["PROBABLE_DATA_QUALITY_ISSUE", "INGESTION_REJECTED", "POSSIBLE_GENUINE_EVENT", "NORMAL"],
        expected_sensor_health_direction="STABLE",
        expected_source_health="HEALTHY",
        expected_correction="NONE",
        expected_ws_event_type="NONE",
        expected_qc_status="ERROR",
    ),
    ScenarioDefinition(
        scenario_id="SV19",
        name="Multivariate Inconsistency",
        category=AnomalyCategory.MULTIVARIATE_FAULT,
        target_stations=["AWS_REG_018"],
        description="Temperature leaps to 42.0°C while relative humidity concurrently surges to 98% under steady pressure.",
        injection_start_step=140,
        injection_end_step=142,
        anomaly_type="MULTIVARIATE_INCONSISTENCY",
        parameters={"temp_c": 42.0, "rh_pct": 98.0},
        expected_detection=True,
        expected_decision="PROBABLE_SENSOR_ANOMALY",
        accepted_decisions=["PROBABLE_SENSOR_ANOMALY"],
        expected_sensor_health_direction="DECREASING",
        expected_source_health="HEALTHY",
        expected_correction="GENERATED",
        expected_ws_event_type="ANOMALY_CREATED",
        expected_qc_status="VALID",
    ),
    ScenarioDefinition(
        scenario_id="SV20",
        name="Spatial Outlier",
        category=AnomalyCategory.SPATIAL_FAULT,
        target_stations=["AWS_REG_019"],
        description="Single isolated station reading +10.5°C above all surrounding neighbors.",
        injection_start_step=145,
        injection_end_step=147,
        anomaly_type="SPATIAL_OUTLIER",
        parameters={"temp_offset_c": 10.5},
        expected_detection=True,
        expected_decision="PROBABLE_SENSOR_ANOMALY",
        accepted_decisions=["PROBABLE_SENSOR_ANOMALY"],
        expected_sensor_health_direction="DECREASING",
        expected_source_health="HEALTHY",
        expected_correction="GENERATED",
        expected_ws_event_type="ANOMALY_CREATED",
        expected_qc_status="VALID",
    ),
    ScenarioDefinition(
        scenario_id="SV21",
        name="Regional Squall / Cold Pool Event",
        category=AnomalyCategory.GENUINE_METEOROLOGICAL_EVENT,
        target_stations=["AWS_DEL_001", "AWS_DEL_002", "AWS_DEL_003", "AWS_DEL_004", "AWS_DEL_005"],
        description="Coherent cold pool passage across the Delhi cluster: all 5 stations experience simultaneous -8.0°C drop, +28% RH surge, and +3.5 hPa pressure spike.",
        injection_start_step=155,
        injection_end_step=163,
        anomaly_type="REGIONAL_EVENT",
        parameters={"temp_drop_c": -8.0, "rh_surge_pct": 28.0, "slp_jump_hpa": 3.5},
        expected_detection=True,
        expected_decision="POSSIBLE_GENUINE_EVENT",
        accepted_decisions=["POSSIBLE_GENUINE_EVENT"],
        expected_sensor_health_direction="PROTECTED",
        expected_source_health="HEALTHY",
        expected_correction="NONE",
        expected_ws_event_type="OBSERVATION_UPDATED",
        expected_qc_status="VALID",
    ),
    ScenarioDefinition(
        scenario_id="SV22",
        name="Partial Station Outage",
        category=AnomalyCategory.SOURCE_OR_NETWORK_OUTAGE,
        target_stations=["AWS_REG_011", "AWS_REG_012", "AWS_REG_013"],
        description="3 regional stations stop transmitting observations due to localized transmission failure.",
        injection_start_step=170,
        injection_end_step=185,
        anomaly_type="PARTIAL_OUTAGE",
        expected_detection=False,
        expected_decision="NOT_APPLICABLE",
        accepted_decisions=["NOT_APPLICABLE", "NO_OBSERVATION", "NORMAL"],
        expected_sensor_health_direction="STABLE",
        expected_source_health="STALE",
        expected_correction="NONE",
        expected_ws_event_type="SYSTEM_STATUS_CHANGED",
        expected_qc_status="MISSING",
    ),
    ScenarioDefinition(
        scenario_id="SV23",
        name="Full Source Disconnection",
        category=AnomalyCategory.SOURCE_OR_NETWORK_OUTAGE,
        target_stations=["ALL_20_STATIONS"],
        description="Complete upstream network disconnect causing all 20 stations to cease transmitting.",
        injection_start_step=190,
        injection_end_step=210,
        anomaly_type="FULL_SOURCE_OUTAGE",
        expected_detection=False,
        expected_decision="NOT_APPLICABLE",
        accepted_decisions=["NOT_APPLICABLE", "NO_OBSERVATION", "POSSIBLE_GENUINE_EVENT", "NORMAL", "DISCONNECTED"],
        expected_sensor_health_direction="STABLE",
        expected_source_health="DISCONNECTED",
        expected_correction="NONE",
        expected_ws_event_type="SYSTEM_STATUS_CHANGED",
        expected_qc_status="UNKNOWN",
    ),
    ScenarioDefinition(
        scenario_id="SV24",
        name="Source Reconnection & Recovery",
        category=AnomalyCategory.SOURCE_OR_NETWORK_OUTAGE,
        target_stations=["ALL_20_STATIONS"],
        description="Upstream source recovers and normal 20-station telemetry resumes.",
        injection_start_step=216,
        injection_end_step=240,
        anomaly_type="SOURCE_RECOVERY",
        expected_detection=False,
        expected_decision="NORMAL",
        accepted_decisions=["NORMAL", "POSSIBLE_GENUINE_EVENT"],
        expected_sensor_health_direction="RECOVERING",
        expected_source_health="HEALTHY",
        expected_correction="NONE",
        expected_ws_event_type="OBSERVATION_UPDATED",
        expected_qc_status="VALID",
    ),
]


def get_scenario_by_id(scenario_id: str) -> Optional[ScenarioDefinition]:
    """Retrieve scenario definition by its SV identifier."""
    sid = scenario_id.upper().strip()
    for sc in SCENARIO_DEFINITIONS:
        if sc.scenario_id == sid:
            return sc
    return None
